### numpy introduction

In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Array

### FOR ONE DIMENSION

In [5]:
a = np.arange(6) 
print(a)

[0 1 2 3 4 5]


In [6]:
a.shape

(6,)

### FOR TWO DIMENSIONS

In [8]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [9]:
a2.shape

(1, 6)

### FOR THREE DIMENSIONS

In [10]:
a3 = a2[np.newaxis, :]
print(a3)

[[[0 1 2 3 4 5]]]


In [11]:
a3.shape

(1, 1, 6)

**Assignments:** why do we have 1D,2D,3D arrays and where we need them in data science?

### creating arrays with numpy

In [12]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6,7),(4,5,6,7,8,9,10)])

In [15]:
print(b)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(7,)

In [16]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

In [25]:
type(a)  #type of array

numpy.ndarray

In [26]:
a.dtype  #data type of array elements

dtype('int64')

### initialize arrays

In [19]:
zeros = np.zeros((3,5)) #(rows,columns)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

data generate using numpy 

In [22]:
full = np.full((2,5), 5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

creating an identity matrix

In [24]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### array attributes

In [27]:
a.shape

(7,)

In [30]:
len(a)  # give us the length elements in array

7

In [31]:
b.size # give us the numbers of elements in array

14

In [29]:
b.ndim #give us the dimension of array

2

### basic operations 

In [32]:
g = a - b
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [34]:
h = a + b  # addition
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [36]:
h1 = np.add(a,b)  # another method of addition
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [37]:
# multiplication
i = a*b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [38]:
# division
k = a / b
k

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [40]:
# square of each element
l = a **2
l

array([ 1,  4,  9, 16, 25, 36, 49])