### Numpy-part : 2

In [3]:
import numpy as np

In [5]:
empty = np.empty((2,3))
print (empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.44898671e-307 2.67018234e-306 1.05699581e-307]]


In [7]:
print(empty[1])

[3.44898671e-307 2.67018234e-306 1.05699581e-307]


In [10]:
x = np.arange(6)
(x)

array([0, 1, 2, 3, 4, 5])

In [15]:
# array of even numbers from 0 to 22
even = np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [16]:
# array of odd numbers from 0 to 23
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [19]:
### specific difference between numbers
diff = np.arange(0,23,3.5)# 3.5 is the difference between numbers
diff

array([ 0. ,  3.5,  7. , 10.5, 14. , 17.5, 21. ])

In [21]:
lin = np.linspace(0, 10, num=15) # 15 the number of elements
lin

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [22]:
lin.dtype

dtype('float64')

In [27]:
# define the dtype of array

x = np.ones(3,dtype=np.float64)# for ones array
x

array([1., 1., 1.])

In [ ]:
x = np.arange(0,22.6,1.5, dtype=np.float64) # for arange array
x

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5])

In [35]:
x = np.arange(0,22.6,1.5, dtype=np.int64)# after int use that's all number roundoff
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### **assignment**: what is the difference between int32, 64ya float 32, 64, 16..... in ka kia matlb hai?  why do we use one and not the other one?

In [36]:
# sorting an array
arr = np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [37]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

### concatenate 1D array

In [38]:
a= np.array([1,2,3,4,5,])
b= np.array([6,7,8,9,10])

In [39]:
# concatenate these arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### concatenate 2D arrays

In [64]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

b = np.array([[7, 8, 9]])     # shape (3,)


In [65]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
b

array([[7, 8, 9]])

In [67]:
# concatenate a & b
z = np.concatenate((a,b))
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
w = np.array([[5,1],[7,1]]) # 2*2 array
x = np.array([[1,2],[3,4]]) # 2*2 array

In [70]:
np.concatenate((w,x), axis=0)

array([[5, 1],
       [7, 1],
       [1, 2],
       [3, 4]])

In [71]:
np.concatenate((w,x), axis=1)

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

### 3D array

In [89]:
array_axample = np.array([[[0,1,2,3],
                        [4,5,6,7]],    

                        [[0,1,2,3,],
                        [4,5,6,7]],
                        
                        [[0,1,2,3],
                        [4,5,6,7]]]) 
array_axample                                           

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [90]:
array_axample .ndim


3

In [91]:
array_axample .size

24

In [93]:
len(array_axample)

3

In [94]:
array_axample .dtype

dtype('int64')

In [95]:
array_axample.shape

(3, 2, 4)

In [104]:
# create 3D array of size (3,1,4)
a1 = np.array([[[0,1,2,3]],
                        [[4,5,6,7]],
                        [[8,9,10,11]]])
a1.shape

(3, 1, 4)

In [105]:
#reshape the a1
a2 = a1.reshape(6,2)
a2.shape


(6, 2)

In [106]:
a1

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [107]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [120]:
a2.reshape(3,1,4)

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [121]:
# create a 1D array
an = np.array([2,1,5,3,7,4,6,8])
an.shape

(8,)

In [122]:
# convert that into 2D array
an[np.newaxis, :].shape

(1, 8)

In [124]:
b= an[np.newaxis, :]
b

array([[2, 1, 5, 3, 7, 4, 6, 8]])

In [125]:
c =an[: , np.newaxis]
c

array([[2],
       [1],
       [5],
       [3],
       [7],
       [4],
       [6],
       [8]])

### indexing and slicing

In [130]:
ay = np.array([1,2,3,4,5,6,7,8])
ay

array([1, 2, 3, 4, 5, 6, 7, 8])

In [131]:
ay[2]

np.int64(3)

In [132]:
ay[2:5]

array([3, 4, 5])

In [133]:
ay[-4:]

array([5, 6, 7, 8])

In [134]:
ay[-4:-2]

array([5, 6])

In [135]:
ay[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [137]:
jk=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
jk

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
jk[2]

array([ 9, 10, 11, 12])

In [140]:
jk[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [141]:
jk[jk < 5]

array([1, 2, 3, 4])

In [142]:
jk[jk > 7]

array([ 8,  9, 10, 11, 12])

In [144]:
jk[jk <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
jk[jk % 3 == 0]

array([ 3,  6,  9, 12])

In [147]:
# use two conditions
jk[(jk > 2) & (jk < 10)]

array([3, 4, 5, 6, 7, 8, 9])

In [151]:
# use three conditions and filter the arrays
jk[(jk > 2) & (jk < 11) & (jk % 2 == 0)]

array([ 4,  6,  8, 10])

In [153]:
jk[(jk > 2) | (jk < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])